SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

DROP TABLE USERS, USER_PI, PI_POT, POTS, PLANT_CONFIGS, COMMANDS, PIS, SENSOR_DATA;

CREATE TABLE `USERS` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`USERNAME` VARCHAR(255) NOT NULL UNIQUE,
	`PASSWORD` VARCHAR(255) NOT NULL,
	`AUTHKEY` VARCHAR(255) NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `USER_PI` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`USER_ID` INT NOT NULL,
	`PI_ID` INT NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `PI_POT` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`PI_ID` INT NOT NULL,
	`POT_ID` INT NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `POTS` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`NAME` VARCHAR(255) NOT NULL,
	`PLANT_CONFIG_ID` INT NOT NULL,
	`SUNRISE` TIME NOT NULL,
	`SUNSET` TIME NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `PLANT_CONFIGS` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`PLANT_CODE` VARCHAR(255) NOT NULL,
	`PLANT_NAME` VARCHAR(255) NOT NULL,
	`REQ_TEMP` FLOAT NOT NULL,
	`REQ_MOIST` FLOAT NOT NULL,
	`REQ_LIGHT` FLOAT NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `COMMANDS` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`POT_ID` INT NOT NULL,
	`TIMESTAMP` DATETIME NOT NULL,
	`TASK` VARCHAR(255) NOT NULL,
	`DELETED` INT NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `PIS` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`NAME` VARCHAR(255) NOT NULL,
	`MAC_ADDRESS` VARCHAR(255) NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `SENSOR_DATA` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`POT_ID` INT NOT NULL,
	`TIMESTAMP` DATETIME NOT NULL,
	`TEMPERATURE` FLOAT NOT NULL,
	`MOISTURE` FLOAT NOT NULL,
	`LIGHT` FLOAT NOT NULL,
	`LAMP_ON` INT NOT NULL,
	`WATERTANK_EMPTY` INT NOT NULL,
	`CONNECTION_DOWN` INT NOT NULL,
	PRIMARY KEY (`ID`)
);

ALTER TABLE `USER_PI` ADD CONSTRAINT `USER_PI_FK0` FOREIGN KEY (`USER_ID`) REFERENCES `USERS`(`ID`);

ALTER TABLE `USER_PI` ADD CONSTRAINT `USER_PI_FK1` FOREIGN KEY (`PI_ID`) REFERENCES `PIS`(`ID`);

ALTER TABLE `PI_POT` ADD CONSTRAINT `PI_POT_FK0` FOREIGN KEY (`PI_ID`) REFERENCES `PIS`(`ID`);

ALTER TABLE `PI_POT` ADD CONSTRAINT `PI_POT_FK1` FOREIGN KEY (`POT_ID`) REFERENCES `POTS`(`ID`);

ALTER TABLE `POTS` ADD CONSTRAINT `POTS_FK0` FOREIGN KEY (`PLANT_CONFIG_ID`) REFERENCES `PLANT_CONFIGS`(`ID`);

ALTER TABLE `COMMANDS` ADD CONSTRAINT `COMMANDS_FK0` FOREIGN KEY (`POT_ID`) REFERENCES `POTS`(`ID`);

ALTER TABLE `SENSOR_DATA` ADD CONSTRAINT `SENSOR_DATA_FK0` FOREIGN KEY (`POT_ID`) REFERENCES `POTS`(`ID`);

INSERT INTO USERS(USERNAME, PASSWORD, AUTHKEY) VALUES('SPETI', 'ITEPS', 'SPETIAUTHKEY');
INSERT INTO PIS(NAME, MAC_ADDRESS) VALUES('OTTHONI', 'B8:27:EB:CE:9E:44');
INSERT INTO PLANT_CONFIGS(PLANT_CODE, PLANT_NAME, REQ_TEMP, REQ_MOIST, REQ_LIGHT) VALUES('001', 'AVOCADO', 101.01, 202.02, 303.03);
INSERT INTO POTS(NAME, PLANT_CONFIG_ID, SUNRISE, SUNSET) VALUES('AVOCADO POT', 1, "7:00:00", "18:30:00");
INSERT INTO POTS(NAME, PLANT_CONFIG_ID, SUNRISE, SUNSET) VALUES('masik avocado POT', 2, "6:30:00", "19:00:00");
INSERT INTO USER_PI(USER_ID, PI_ID) VALUES(1, 1);
INSERT INTO PI_POT(PI_ID, POT_ID) VALUES(1, 1);

SELECT * FROM USERS;
SELECT * FROM PIS;
SELECT * FROM PLANT_CONFIGS;
SELECT * FROM POTS;
SELECT * FROM USER_PI;
SELECT * FROM PI_POT;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;